windcockpit/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'sessions', views.SessionViewSet)

app_name = "windcockpit"
urlpatterns = [
    path("", views.index, name="index"),
    path("sessions/", views.sessions, name="sessions"),
    path("sessions/<int:session_id>/", views.session, name="session"),

    path('api/', include(router.urls)),
]

winduniverse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("wp/", include("windcockpit.urls")),
    path('admin/', admin.site.urls),
]

windcockpit/models.py
from django.db import models


class Spot(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Session(models.Model):
    sport = models.CharField(max_length=200)
    date = models.DateTimeField("date of session")
    spot = models.ForeignKey(Spot, on_delete=models.RESTRICT)

    # distance in meter
    distance = models.FloatField(default=0)

    # max speed in m/s
    max_speed = models.FloatField(default=0)

    # duration in minutes
    duration = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.date}: {self.sport} in {self.spot}'

windcockpit/forms.py
from django.forms import ModelForm

from windcockpit.models import Session
from windcockpit.widgets import DatePickerInput


class SessionForm(ModelForm):
    class Meta:
        model = Session
        fields = ["sport", "spot", "date"]
        widgets = {
            "date": DatePickerInput()
        }

windcockpit/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from rest_framework import viewsets
from rest_framework import permissions

from windcockpit.forms import SessionForm
from windcockpit.models import Session
from windcockpit.serializiers import SessionSerializer


def index(request):
    return HttpResponse("Hello, world. You're at the windcockpit index.")


def sessions(request):
    latest_session_list = Session.objects.order_by("-date")
    return render(request, "windcockpit/sessions.html", {
        "latest_session_list": latest_session_list
    })


def session(request, session_id):
    s = get_object_or_404(Session, pk=session_id)

    if request.method == "POST":
        form = SessionForm(request.POST, instance=s)
        if form.is_valid():
            form.save()
        return redirect("windcockpit:sessions")
    else:
        form = SessionForm(instance=s)
        return render(request, "windcockpit/session.html", {"form": form})


class SessionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Session.objects.all().order_by('-date')
    serializer_class = SessionSerializer
    permission_classes = [permissions.AllowAny]

windcockpit/templates/windcockpit/base.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'windcockpit/style.css' %}">
    <title>Windcockpit</title>
</head>

<body>
{% block content %}
{% endblock content %}
</body>
</html>

windcockpit/templates/windcockpit/session.html
{% extends "windcockpit/base.html" %}
{% block content %}
    <h1>Session Details</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

windcockpit/templates/windcockpit/sessions.html
{% extends "windcockpit/base.html" %}
{% block content %}
<h1>Sessions</h1>
{% if latest_session_list %}
    <ul>
        {% for session in latest_session_list %}
            <li>
                <a href="{% url 'windcockpit:session' session.id %}">
                    {{ session.date |date:'Y-m-d H:i' }}: {{ session.sport }} in {{ session.spot.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No sessions are available.</p>
{% endif %}
{% endblock %}